import { SidebarProvider } from '@/context/SidebarContext';

export const metadata = {
  title: 'Xone NextJS',
  description: 'Generated by Xone ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          {children}
        </SidebarProvider>
      </body>
    </html>
  )
}
