const routes = {
    login: '/login',
    register: '/register',
    loginMfa: '/two-factor',
    forgotPassword: '/forgot-password',
    roles: '/roles',
    permissions: '/permission',
    users: '/users',
    country: '/country',
    profile: '/profile',
    welcome: '/welcome',
    main: '/',
    notification: '/notification',
    setting: '/settings/general',
    Settingconfig: '/settings/config',
    chat: '/chat',
    customGPT: '/custom-gpt',
    customTemplates: '/custom-templates',
    customGPTAdd: '/custom-gpt/add',
    prompts: '/prompts',
    dataControls: '/settings/data-controls',
    settingMembers: '/settings/members',
    settingReports: '/settings/reports',
    settingBilling: '/settings/billing',
    docs: '/docs',
    pages: '/pages',
    profileSetting: '/profile-setting',
    twoFactorAuthentication: '/profile-setting/two-factor-authentication',
    dashboard: '/dashboard',  
    companyUser: '/dashboard/company-user',
    settingSubscription: '/settings/subscription',
    sendVerification: '/verification',
    onboard: '/onboard',
    changePassword: '/profile-setting/password',
    testSubscription: '/test-subscription',
    weeklyReport: '/settings/weekly-report',
    creditControl: '/settings/credit-control',
    mcp: '/mcp',
    superSolution: '/settings/super-solution'
};

export default routes;